// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkmjzigfloujahgwwqcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrbWp6aWdmbG91amFoZ3d3cWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjQzOTQsImV4cCI6MjA3MjU0MDM5NH0.hplo4_6cz3-q7A8QJ3rCokr-WX6TAWhuL0YNjKL1leo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});